###########################################
#               DupePatch                 #
#     Made by: MrKitty_Cat And Sxtanna    #
###########################################

Prefix: "&a&Dupe&e&lPatch &7| "

# Enable or Disable the sending of the NotifyMsg. This can have false positives at times, and is only called on successful attempts (Which is not often).
# Sends a notification (%player_name% is replaced with the Player's Name) to players with the permission specified below, defaults to "dupePatch.notify" (Case-Sensitive).
Notification:
  Enabled: true
  Message: "&c&l%player_name%, was caught trying to Drop Glitch!"
  Permission: "dupePatch.notify"
